all: compilemodified compilerunner run

compilemodified:
	javac -classpath .:gridworld.jar ModifiedChameleonCritter.java

compilerunner:
	javac -classpath .:gridworld.jar ModifiedChameleonCritterRunner.java

run:
	java -classpath .:gridworld.jar ModifiedChameleonCritterRunner
