all: compilekid compilerunner run

compilekid:
	javac -classpath .:gridworld.jar ChameleonKid.java

compilerunner:
	javac -classpath .:gridworld.jar ChameleonKidRunner.java

run:
	java -classpath .:gridworld.jar ChameleonKidRunner
