all: compileking compilerunner run

compileking:
	javac -classpath .:gridworld.jar KingCrab.java

compilerunner:
	javac -classpath .:gridworld.jar KingCrabRunner.java

run:
	java -classpath .:gridworld.jar KingCrabRunner
