all: compilecritter compilerunner run

compilecritter:
	javac -classpath .:gridworld.jar BlusterCritter.java

compilerunner:
	javac -classpath .:gridworld.jar BlusterCritterRunner.java

run:
	java -classpath .:gridworld.jar BlusterCritterRunner
