all: compile take run

compile:
	javac -classpath .:gridworld.jar DancingBug.java

take:
	javac -classpath .:gridworld.jar DancingBugRunner.java

run:
	java -classpath .:gridworld.jar DancingBugRunner
