all: compilecritter compilerunner run

compilecritter:
	javac -classpath .:gridworld.jar RockHound.java

compilerunner:
	javac -classpath .:gridworld.jar RockHoundRunner.java

run:
	java -classpath .:gridworld.jar RockHoundRunner
